### ISSUE TITLE
PHP Fatal error:  Declaration of Bugsnag\PsrLogger\BugsnagLogger::log

### ISSUE THREAD

**Issue by Eugene-Melbourne** [bugsnag/bugsnag-psr-logger#54]
### Describe the bug
after I upgreded to PHP 8  bugsnag is not working

PHP Fatal error:  Declaration of Bugsnag\PsrLogger\BugsnagLogger::log(mixed $level, Stringable|string $message, array $context = []): void must be compatible with PsrExt\Log\LoggerInterface::log($level, $message, array $context = []) in /var/www/default/vendor/bugsnag/bugsnag-psr-logger/src/BugsnagLogger.php on line 66

### Environment
* Bugsnag version: v2.24.0
* PHP version: 8.0
* Composer version: 2.3.5
* Laravel version: 8.83.13
* PSR-3 implementation and version: 2.0.0

### Details
I cannot upgrade to V3 because:

symfony/console
        "conflict": {  "psr/log": ">=3",

**Comment by Eugene-Melbourne** [comment]
It may have something to do with php8.0-psr
I have it installed 

https://linux-packages.com/ubuntu-jammy-jellyfish/package/php80-psr

**Comment by Eugene-Melbourne** [comment]
In my previous comment I mention the php8.0-psr. Bugsnag does not work with this php module.

**Comment by fakharksa** [comment]
The issue goes away when on line 66  in /[Your_Project_Folder]/vendor/bugsnag/bugsnag-psr-logger/src/BugsnagLogger.php, i removed the Type-hint for the second argument of the function as below:

Line 66 (Original): 
`public function log(mixed $level, string|\Stringable $message, array $context = []): void`
to (changed)...
`public function log(mixed $level, $message, array $context = []): void`

Note: Better, also remove mixed type-hint before first argument of that function.

**Comment by Eugene-Melbourne** [comment]
@fakharksa  , You should not touch files in `[Your_Project_Folder]/vendor` folder. It is up to package maintainer to fix this bug, or a brave contributor can do it.

**Comment by johnkiely1** [comment]
Hi @Eugene-Melbourne. We are going to try and reproduce exactly what you are seeing.  I will let you know as soon as we have more information.

**Comment by johnkiely1** [comment]
On further investigation, it looks like the linux package referenced above uses PSR log v1: [GitHub - jbboehr/php-psr: PHP extension providing the accepted PSR interfaces](https://github.com/jbboehr/php-psr) 

Support for PSR log v1 was dropped in bugsnag-psr-logger v2.0: [bugsnag-psr-logger/CHANGELOG.md at master · bugsnag/bugsnag-psr-logger](https://github.com/bugsnag/bugsnag-psr-logger/blob/master/CHANGELOG.md#200-2022-01-12)

So to resolve this we would suggest the following:

Option A: Remove the linux package, and install all dependencies through composer

Option B: You could downgrade the version of the psr logger to use a v1.x release by pinning to bugsnag-psr-logger v1.x.

Do let us know if either of these options work for you.

**Comment by fakharksa** [comment]
> @fakharksa , You should not touch files in `[Your_Project_Folder]/vendor` folder. It is up to package maintainer to fix this bug, or a brave contributor can do it.

### Technical Concern:
This is merely an "Compatibility" issue in library's code, due to how "(Data-) Type Hinting" works. So, in order to make code adaptive / compatible, the solution i provided in my last comment is the best way to go for now. 

Link to my last comment:
https://github.com/bugsnag/bugsnag-psr-logger/issues/54#issuecomment-1146864083

### Your Strategical Concern (Who should update the library code? ) :
It is often considered that all level / kinds of updates should always come only through vendor of the package, however when things get stuck at the very first step (like, at "installation / configuration" of dependency of the Project), it is not wisdom to hold the project and wait for the Vendor (or, bold contributor/s) to apply even a minor fix. My opinion only.
